name: Tusk Drift

on:
  pull_request:

jobs:
  tusk-drift:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0

      - name: Install dependencies
        run: npm ci

      - name: Install Tusk Drift CLI
        # This assumes that /usr/local/bin is in the PATH (generally the case on GitHub Actions runners)
        # If not, we can add it to the PATH by running:
        # echo "$HOME/.local/bin" >> $GITHUB_PATH
        run: |
          curl -fsSL https://raw.githubusercontent.com/Use-Tusk/tusk-drift-cli/main/install.sh | sh
          tusk --version

      - name: Run Tusk Drift trace tests
        # CLI automatically picks up commit SHA, PR number, branch name,
        # and external check run ID from CI environment variables.
        run: |
          tusk run -c -p --ci
        env:
          TUSK_API_KEY: tusk-9b03ffcacb285a6e3ca4ba8e883ba4ce
